version: '3'
services:
    link:
        container_name: link-service
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app/src
    postgres:
        container_name: postgres
        image: 'postgres'
        environment:
            POSTGRES_USER: 'userDB'
            POSTGRES_PASSWORD: 'userDB'
            POSTGRES_DB: 'users'
        ports:
            - '5432:5432'
